// Generated from database [029] in server [.\SQLEXPRESS2008
// Do NOT edit this file. If needed make additions in a separate partial class
using System;
using System.IO;
using System.Runtime.Serialization;
namespace MAR.DataAccess.Tables {

    // Mirrors DB Table bk_TDE_Oct_2
    [Serializable()]
    public partial class bk_TDE_Oct_2Record : BaseRecord
	{
        public int TicketDetalleID;
        public int TicketID;
        public char TDeQP;
        public char TDeNumero;
        public double TDeCantidad;
        public decimal TDeCosto;
        public decimal TDePago;
        public char TDePagoTipo;
    }

    // Mirrors DB Table bk_TK_Oct_2
    [Serializable()]
    public partial class bk_TK_Oct_2Record : BaseRecord
	{
        public int TicketID;
        public int GrupoID;
        public int LoteriaID;
        public int RiferoID;
        public int BancaID;
        public int UsuarioID;
        public DateTime TicFecha;
        public string TicCliente;
        public string TicCedula;
        public string TicNumero;
        public bool TicNulo;
        public decimal TicCosto;
        public decimal TicPago;
        public decimal TicSolicitud;
        public bool TicPagado;
        public int PagoID;
    }

    // Mirrors DB Table Borrar
    [Serializable()]
    public partial class BorrarRecord : BaseRecord
	{
        public int? RiferoID;
    }

    // Mirrors DB Table CL_Cliente
    [Serializable()]
    public partial class CL_ClienteRecord : BaseRecord
	{
        public int ClienteID;
        public string Nombres;
        public string Apellidos;
        public string Documento;
        public int TipoDocumentoID;
        public DateTime FechaCreado;
        public DateTime? UltimaAccion;
        public bool Activo;
    }

    // Mirrors DB Table CL_ClienteCampo
    [Serializable()]
    public partial class CL_ClienteCampoRecord : BaseRecord
	{
        public int ClienteCampoID;
        public string Nombre;
        public string Referencia;
        public string TipoDato;
        public string OpcionesReferencias;
        public string OpcionesNombres;
        public bool Activo;
        public int? ClienteID;
    }

    // Mirrors DB Table CL_ClienteDetalle
    [Serializable()]
    public partial class CL_ClienteDetalleRecord : BaseRecord
	{
        public int ClienteDetalleID;
        public int ClienteID;
        public int ClienteCampoID;
        public string Referencia;
        public string ValorText;
        public double? ValorMonto;
    }

    // Mirrors DB Table CL_Recibo
    [Serializable()]
    public partial class CL_ReciboRecord : BaseRecord
	{
        public int ReciboID;
        public string Referencia;
        public string Serie;
        public int SolicitudID;
        public DateTime Fecha;
        public int BancaID;
        public int UsuarioID;
        public int? ClienteID;
        public decimal Ingresos;
        public decimal? Impuestos;
        public decimal? Descuentos;
        public int MonedaID;
    }

    // Mirrors DB Table CL_ReciboDetalle
    [Serializable()]
    public partial class CL_ReciboDetalleRecord : BaseRecord
	{
        public int ReciboDetalleID;
        public int? ReciboID;
        public int TransaccionID;
        public string Tipo;
        public string Estado;
        public decimal Ingreso;
        public decimal? Impuesto;
        public decimal? Descuento;
    }

    // Mirrors DB Table DAlerta
    [Serializable()]
    public partial class DAlertaRecord : BaseRecord
	{
        public int AlertaID;
        public string Entidad;
        public string Mensaje;
        public string Usuario;
        public string Origen;
        public int Nivel;
        public DateTime Fecha;
    }

    // Mirrors DB Table DBilleteDetalle
    [Serializable()]
    public partial class DBilleteDetalleRecord : BaseRecord
	{
        public int BilleteDetalleID;
        public int TicketDetalleID;
        public string Serial;
        public DateTime HoraRequest;
        public DateTime HoraResponse;
        public int NumeroSorteo;
    }

    // Mirrors DB Table DControlDetalle
    [Serializable()]
    public partial class DControlDetalleRecord : BaseRecord
	{
        public int ControlDetalleID;
        public int ControlID;
        public char CDeQP;
        public char CDeNumero;
        public int RiferoID;
        public int LoteriaID;
    }

    // Mirrors DB Table DControles
    [Serializable()]
    public partial class DControlesRecord : BaseRecord
	{
        public int ControlID;
        public int GrupoID;
        public string ConNombre;
        public int ConLimite;
        public int ConPorUserID;
        public string ConColor;
        public char ConQP;
    }

    // Mirrors DB Table dcontroles_bk
    [Serializable()]
    public partial class dcontroles_bkRecord : BaseRecord
	{
        public int ControlID;
        public int GrupoID;
        public string ConNombre;
        public int ConLimite;
        public int ConPorUserID;
        public string ConColor;
        public char ConQP;
    }

    // Mirrors DB Table DImpuestoRetenido
    [Serializable()]
    public partial class DImpuestoRetenidoRecord : BaseRecord
	{
        public int ImpuestoRetenidoID;
        public int TicketID;
        public DateTime Fecha;
        public int BancaID;
        public decimal TotalSaco;
        public decimal Retenido;
        public string TicNumero;
        public int TipoImpuestoID;
    }

    // Mirrors DB Table DListaDia
    [Serializable()]
    public partial class DListaDiaRecord : BaseRecord
	{
        public int ListaDiaID;
        public string LDiNumero;
        public int LoteriaID;
        public int BancaID;
        public double LDiCantidad;
        public char LDiQP;
        public int RiferoID;
        public int GrupoID;
    }

    // Mirrors DB Table DMensajes
    [Serializable()]
    public partial class DMensajesRecord : BaseRecord
	{
        public int MensajeID;
        public string MenTipo;
        public string MenAsunto;
        public string MenContenido;
        public DateTime MenFecha;
        public string MenDestino;
        public char MenDireccion;
        public int BancaID;
        public string MenOrigen;
        public bool MenLeido;
    }

    // Mirrors DB Table DRiesgoDia
    [Serializable()]
    public partial class DRiesgoDiaRecord : BaseRecord
	{
        public int RiesgoID;
        public int LoteriaID;
        public char RieQP;
        public double RieMontoVenta;
        public double RieComision;
        public double RieSaca;
        public double RieActual;
        public double RieMaximo;
        public double RieVenta;
        public double RieLimite;
    }

    // Mirrors DB Table DTicketDetalle
    [Serializable()]
    public partial class DTicketDetalleRecord : BaseRecord
	{
        public int TicketDetalleID;
        public int TicketID;
        public char TDeQP;
        public string TDeNumero;
        public double TDeCantidad;
        public decimal TDeCosto;
        public decimal TDePago;
        public char TDePagoTipo;
        public string TDeLlave;
    }

    // Mirrors DB Table DTickets
    [Serializable()]
    public partial class DTicketsRecord : BaseRecord
	{
        public int TicketID;
        public int GrupoID;
        public int LoteriaID;
        public int RiferoID;
        public int BancaID;
        public int UsuarioID;
        public DateTime TicFecha;
        public string TicCliente;
        public string TicCedula;
        public string TicNumero;
        public bool TicNulo;
        public decimal TicCosto;
        public decimal TicPago;
        public decimal TicSolicitud;
        public bool TicPagado;
        public int PagoID;
    }

    // Mirrors DB Table DWebProductoDetalle
    [Serializable()]
    public partial class DWebProductoDetalleRecord : BaseRecord
	{
        public int PinID;
        public int WebProductoID;
        public string FieldKey;
        public string FieldValue;
    }

    // Mirrors DB Table HAlerta
    [Serializable()]
    public partial class HAlertaRecord : BaseRecord
	{
        public int HAlertaID;
        public int? AlertaID;
        public string Entidad;
        public string Mensaje;
        public string Usuario;
        public string Origen;
        public int? Nivel;
        public DateTime? Fecha;
    }

    // Mirrors DB Table HCertificados
    [Serializable()]
    public partial class HCertificadosRecord : BaseRecord
	{
        public int CertificadoID;
        public int CerNumero;
        public int BancaID;
        public int CerHwKey;
        public DateTime CerFecha;
    }

    // Mirrors DB Table HClaveLocal
    [Serializable()]
    public partial class HClaveLocalRecord : BaseRecord
	{
        public int ClaveLocalID;
        public int BancaID;
        public string CLoLlave;
        public string CLoAutoriza;
        public int CLoHora;
        public DateTime CLoFecha;
        public string CLoIP;
        public string CLoUsuario;
        public bool CLoHistorico;
    }

    // Mirrors DB Table HContabilidad
    [Serializable()]
    public partial class HContabilidadRecord : BaseRecord
	{
        public int ContabilidadID;
        public int? CuentaID;
        public string CueNombre;
        public string CueNumero;
        public int BancaID;
        public DateTime ConFecha;
    }

    // Mirrors DB Table HControles
    [Serializable()]
    public partial class HControlesRecord : BaseRecord
	{
        public int HControlID;
        public int ControlID;
        public int LoteriaID;
        public int GrupoID;
        public string ConNombre;
        public int ConLimite;
        public int ConPorUserID;
        public int RiferoID;
        public DateTime ConFecha;
    }

    // Mirrors DB Table HDestinos
    [Serializable()]
    public partial class HDestinosRecord : BaseRecord
	{
        public int DestinoID;
        public string DesIPAddress;
        public DateTime DesInicio;
        public DateTime DesAlive;
    }

    // Mirrors DB Table HEstatusDias
    [Serializable()]
    public partial class HEstatusDiasRecord : BaseRecord
	{
        public int EstatusDiaID;
        public DateTime EDiFecha;
        public int GrupoID;
        public int LoteriaID;
        public DateTime? EDiInicioVentaFecha;
        public int EDiInicioVentaUserID;
        public bool EDiVentaIniciada;
        public DateTime? EDiCierreVentaFecha;
        public int EDiCierreVentaUserID;
        public bool EDiVentaCerrada;
        public DateTime? EDiEntradaPremiosFecha;
        public int EDiEntradaPremiosUserID;
        public bool EDiPremiosDentro;
        public DateTime? EDiCierreDiaFecha;
        public int EDiCierreDiaUserID;
        public bool EDiDiaCerrado;
        public char PremioQ1;
        public char PremioQ2;
        public char PremioQ3;
        public decimal? EDiClave;
    }

    // Mirrors DB Table HImpuestoRetenido
    [Serializable()]
    public partial class HImpuestoRetenidoRecord : BaseRecord
	{
        public int HImpuestoRetenidoID;
        public int ImpuestoRetenidoID;
        public int TicketID;
        public DateTime Fecha;
        public int BancaID;
        public decimal TotalSaco;
        public decimal Retenido;
        public string TicNumero;
        public int TipoImpuestoID;
    }

    // Mirrors DB Table HLog
    [Serializable()]
    public partial class HLogRecord : BaseRecord
	{
        public int LogID;
        public string LogTipo;
        public string LogComentario;
        public DateTime LogFecha;
        public string UsuarioID;
        public string SecRemoteIP;
        public int BancaID;
    }

    // Mirrors DB Table HMensajes
    [Serializable()]
    public partial class HMensajesRecord : BaseRecord
	{
        public int HMensajeID;
        public int MensajeID;
        public string MenTipo;
        public string MenAsunto;
        public string MenContenido;
        public DateTime MenFecha;
        public string MenDestino;
        public char MenDireccion;
        public int BancaID;
        public string MenOrigen;
        public bool MenLeido;
    }

    // Mirrors DB Table HPagos
    [Serializable()]
    public partial class HPagosRecord : BaseRecord
	{
        public int PagoID;
        public DateTime PagFecha;
        public int BancaID;
        public string BanContacto;
        public decimal PagMonto;
        public string PagUsuario;
        public string TicNumero;
        public DateTime EdiFecha;
        public int LoteriaID;
        public DateTime? PagDia;
    }

    // Mirrors DB Table HRebotes
    [Serializable()]
    public partial class HRebotesRecord : BaseRecord
	{
        public int ReboteID;
        public DateTime RebFecha;
        public int ConsorcioID;
        public int LoteriaID;
        public decimal RebTotal;
        public decimal RebComision;
        public decimal RebNeto;
        public string RebTicketAqui;
        public string RebTicketAlla;
        public decimal RebSaco;
        public decimal RebBalance;
        public bool RebNulo;
    }

    // Mirrors DB Table HResumen
    [Serializable()]
    public partial class HResumenRecord : BaseRecord
	{
        public int ResumenID;
        public DateTime? EDiFecha;
        public int? GrupoID;
        public int? RiferoID;
        public int? BancaID;
        public int? LoteriaID;
        public double? BanComisionQ;
        public double? BanComisionP;
        public double? BanComisionT;
        public char? Primero;
        public char? Segundo;
        public char? Tercero;
        public double? CVQuinielas;
        public decimal? VQuinielas;
        public double? CVBilletes;
        public decimal? VBilletes;
        public double? CVPales;
        public decimal? VPales;
        public double? CVTripletas;
        public decimal? VTripletas;
        public double? CPrimero;
        public double? CSegundo;
        public double? CTercero;
        public double? CPales;
        public double? CTripletas;
        public decimal? MPrimero;
        public decimal? MSegundo;
        public decimal? MTercero;
        public decimal? MPales;
        public decimal? MTripletas;
        public bool ResVFuera;
        public decimal? MPagado;
        public int? CVTickets;
        public DateTime ResCierre;
        public double? RifDescuento;
        public decimal? ISRRetenido;
    }

    // Mirrors DB Table HSecurityLog
    [Serializable()]
    public partial class HSecurityLogRecord : BaseRecord
	{
        public int SecurityLogID;
        public int LogID;
        public string SecTipo;
        public string SecComentario;
        public DateTime SecFecha;
        public string UsuarioID;
        public string SecRemoteIP;
        public int BancaID;
    }

    // Mirrors DB Table HTicketDetalle
    [Serializable()]
    public partial class HTicketDetalleRecord : BaseRecord
	{
        public int HTicketDetalleID;
        public int TicketDetalleID;
        public int TicketID;
        public char TDeQP;
        public string TDeNumero;
        public double TDeCantidad;
        public decimal TDeCosto;
        public decimal TDePago;
        public char TDePagoTipo;
        public string TDeLlave;
    }

    // Mirrors DB Table HTicketLocalDetalle
    [Serializable()]
    public partial class HTicketLocalDetalleRecord : BaseRecord
	{
        public int TicketLocalDetalleID;
        public int TicketLocalID;
        public char TLDQP;
        public char TLDNumero;
        public double TLDCantidad;
        public decimal TLDCosto;
        public decimal TLDPago;
        public char TLDPagoTipo;
    }

    // Mirrors DB Table HTickets
    [Serializable()]
    public partial class HTicketsRecord : BaseRecord
	{
        public int HTicketID;
        public int TicketID;
        public int GrupoID;
        public int LoteriaID;
        public int RiferoID;
        public int BancaID;
        public int UsuarioID;
        public DateTime TicFecha;
        public string TicCliente;
        public string TicCedula;
        public string TicNumero;
        public bool TicNulo;
        public decimal TicCosto;
        public decimal TicPago;
        public decimal TicSolicitud;
        public bool TicPagado;
        public int PagoID;
    }

    // Mirrors DB Table HTicketsLocal
    [Serializable()]
    public partial class HTicketsLocalRecord : BaseRecord
	{
        public int TicketLocalID;
        public int GrupoID;
        public int LoteriaID;
        public int RiferoID;
        public int BancaID;
        public int UsuarioID;
        public DateTime TLoFecha;
        public string TLoCliente;
        public string TLoCedula;
        public string TLoNumero;
        public bool TLoNulo;
        public decimal TLoCosto;
        public decimal TLoPago;
        public decimal TLoSolicitud;
    }

    // Mirrors DB Table HWebProductoDetalle
    [Serializable()]
    public partial class HWebProductoDetalleRecord : BaseRecord
	{
        public int WebProductoDetalleID;
        public int PinID;
        public int WebProductoID;
        public string FieldKey;
        public string FieldValue;
    }

    // Mirrors DB Table MBancas
    [Serializable()]
    public partial class MBancasRecord : BaseRecord
	{
        public int BancaID;
        public string BanNombre;
        public string BanContacto;
        public string BanDireccion;
        public string BanDireccionIP;
        public string BanTelefono;
        public string BanNumeroLinea;
        public int RiferoID;
        public bool BanActivo;
        public string BanComentario;
        public bool BanValidIP;
        public int BanSesionActual;
        public string BanDireccionActual;
        public int BanUsuarioActual;
        public int BanRePrintTicketID;
        public int BanUltimoTicket;
        public string BanVersion;
        public double BanMaxQuiniela;
        public double BanMaxPale;
        public double BanMaxTriple;
        public double BanComisionQ;
        public double BanComisionP;
        public double BanComisionT;
        public int EsquemaID;
        public DateTime BanAlive;
        public DateTime BanFirstContact;
        public DateTime BanLastContact;
        public bool BanAnula;
        public bool BanVLocal;
        public bool BanGanadores;
        public double BanMaxQuinielaLoc;
        public double BanMaxPaleLoc;
        public double BanMaxTripleLoc;
        public bool BanTarjeta;
        public double BanComisionTarj;
        public int BanTerminalTarj;
        public string BanSerieTarj;
        public bool BanRenta;
        public DateTime BanRegistra;
        public string BanRemoteCMD;
        public double BanMaxSupeLoc;
        public double BanMaxQuinielaTic;
        public double BanMaxPaleTic;
        public double BanMaxTripleTic;
        public int BanSesionWeb;
        public string BanDireccionWeb;
        public int BanUsuarioWeb;
        public double BanMaxSupe;
        public bool BanImpuesto;
        public bool BanPrintRecarga;
        public bool BanPrintReportes;
        public bool? BanBillete;
        public bool? BanServicios;
    }

    // Mirrors DB Table MBancasConfig
    [Serializable()]
    public partial class MBancasConfigRecord : BaseRecord
	{
        public int BancaConfigID;
        public int BancaID;
        public string ConfigKey;
        public string ConfigValue;
        public bool Activo;
    }

    // Mirrors DB Table MConsorcios
    [Serializable()]
    public partial class MConsorciosRecord : BaseRecord
	{
        public int ConsorcioID;
        public string ConNombre;
        public string ConContacto;
        public string ConTelefonos;
        public int ConBancaID;
        public string ConServidor;
    }

    // Mirrors DB Table MCuentas
    [Serializable()]
    public partial class MCuentasRecord : BaseRecord
	{
        public int CuentaID;
        public string CueNombre;
        public string CueNumero;
        public string CueComentario;
        public bool CueActiva;
    }

    // Mirrors DB Table MDiasDefecto
    [Serializable()]
    public partial class MDiasDefectoRecord : BaseRecord
	{
        public int DiaDefectoID;
        public int LoteriaID;
        public int GrupoID;
        public int DDeDia;
        public int DDeHoraInicio;
        public int DDeHoraFin;
        public decimal DDeCostoQ;
        public decimal DDeCostoP;
        public decimal DDeCostoT;
        public decimal DDePagoQ1;
        public decimal DDePagoQ2;
        public decimal DDePagoQ3;
        public decimal DDePagoP1;
        public decimal DDePagoP2;
        public decimal DDePagoP3;
        public decimal DDePagoT1;
        public decimal DDePagoT2;
        public decimal DDePagoT3;
        public double? DDeMaxPale;
        public double? DDeMaxQuiniela;
        public double? DDeMaxTriple;
        public int EsquemaID;
    }

    // Mirrors DB Table MImpuestoRango
    [Serializable()]
    public partial class MImpuestoRangoRecord : BaseRecord
	{
        public int ImpuestoRangoID;
        public DateTime FechaEfectividad;
        public DateTime? FechaExpira;
        public decimal DesdeMonto;
        public decimal HastaMonto;
        public double PorcientoRetencion;
        public bool Activo;
        public int TipoImpuestoID;
    }

    // Mirrors DB Table MNotificaciones
    [Serializable()]
    public partial class MNotificacionesRecord : BaseRecord
	{
        public int NotificacionID;
        public int Tipo;
        public string Nombre;
        public string eMail;
    }

    // Mirrors DB Table MPrecios
    [Serializable()]
    public partial class MPreciosRecord : BaseRecord
	{
        public int PrecioID;
        public int LoteriaID;
        public int GrupoID;
        public double PreCostoQ;
        public double PreCostoP;
        public double PreCostoT;
        public double PrePagoQ1;
        public double PrePagoQ2;
        public double PrePagoQ3;
        public double PrePagoP1;
        public double PrePagoP2;
        public double PrePagoP3;
        public double PrePagoT1;
        public double PrePagoT2;
        public double PrePagoT3;
        public int EsquemaID;
    }

    // Mirrors DB Table MPremioSuperPale
    [Serializable()]
    public partial class MPremioSuperPaleRecord : BaseRecord
	{
        public int PremioSuperPaleID;
        public int LoteriaIdOrigen1;
        public int LoteriaIdOrigen2;
        public int LoteriaIdDestino;
        public bool Activo;
    }

    // Mirrors DB Table MRiferos
    [Serializable()]
    public partial class MRiferosRecord : BaseRecord
	{
        public int RiferoID;
        public string RifNombre;
        public string RifContacto;
        public string RifTelefono;
        public string RifCelular;
        public string RifCedula;
        public string RifComentario;
        public int GrupoID;
        public bool RifActivo;
        public int? ZonaID;
        public double RifDescuento;
        public double RifCaida;
    }

    // Mirrors DB Table MUsuarios
    [Serializable()]
    public partial class MUsuariosRecord : BaseRecord
	{
        public int UsuarioID;
        public string UsuNombre;
        public string UsuApellido;
        public string UsuCedula;
        public DateTime UsuFechaNac;
        public string UsuUserName;
        public string UsuClave;
        public DateTime UsuVenceClave;
        public bool UsuActivo;
        public int UsuNivel;
        public string UsuComentario;
    }

    // Mirrors DB Table MZonaLimites
    [Serializable()]
    public partial class MZonaLimitesRecord : BaseRecord
	{
        public int ZonaLimiteID;
        public int ZonaID;
        public int LoteriaID;
        public double MaxQuiniela;
        public double MaxPale;
        public double MaxTripleta;
    }

    // Mirrors DB Table MZonas
    [Serializable()]
    public partial class MZonasRecord : BaseRecord
	{
        public int ZonaID;
        public string Nombre;
        public bool Activa;
    }

    // Mirrors DB Table PDPines
    [Serializable()]
    public partial class PDPinesRecord : BaseRecord
	{
        public int PinID;
        public int SuplidorID;
        public int CuentaID;
        public int ProductoID;
        public string PinSerial;
        public string PinNumero;
        public string PinReferencia;
        public string PinCodigo;
        public int PinNulo;
        public string PinMensaje;
        public decimal PinSecuencia;
        public char PinFlag;
        public int BancaID;
        public int RiferoID;
        public int GrupoID;
        public DateTime PinFecha;
        public string PinIPAddr;
        public decimal PinCosto;
        public double PinImpuesto;
        public double PinComision;
    }

    // Mirrors DB Table PHPines
    [Serializable()]
    public partial class PHPinesRecord : BaseRecord
	{
        public int HPinID;
        public int PinID;
        public int SuplidorID;
        public int CuentaID;
        public int ProductoID;
        public string PinSerial;
        public string PinNumero;
        public string PinReferencia;
        public string PinCodigo;
        public int PinNulo;
        public string PinMensaje;
        public decimal PinSecuencia;
        public char PinFlag;
        public int BancaID;
        public int RiferoID;
        public int GrupoID;
        public DateTime PinFecha;
        public string PinIPAddr;
        public decimal PinCosto;
        public double PinImpuesto;
        public double PinComision;
        public string ProNombre;
        public string SupNombre;
        public double? ProPrecio;
    }

    // Mirrors DB Table PHVentas
    [Serializable()]
    public partial class PHVentasRecord : BaseRecord
	{
        public int VentaID;
        public DateTime? VenFecha;
        public int? GrupoID;
        public int? RiferoID;
        public int? BancaID;
        public double? BanComision;
        public double? SupComision;
        public double? SupImpuesto;
        public int? SuplidorID;
        public string SupNombre;
        public int? UsuarioID;
        public string Vendedor;
        public double? CTarjetas;
        public decimal? VTarjetas;
    }

    // Mirrors DB Table PHVentas_Productos_PreRebuild
    [Serializable()]
    public partial class PHVentas_Productos_PreRebuildRecord : BaseRecord
	{
        public int VentaID;
        public DateTime? VenFecha;
        public int? GrupoID;
        public int? RiferoID;
        public int? BancaID;
        public double? BanComision;
        public double? SupComision;
        public double? SupImpuesto;
        public int? SuplidorID;
        public string SupNombre;
        public int? UsuarioID;
        public string Vendedor;
        public double? CTarjetas;
        public decimal? VTarjetas;
    }

    // Mirrors DB Table PMCuenta
    [Serializable()]
    public partial class PMCuentaRecord : BaseRecord
	{
        public int CuentaID;
        public string CueNombre;
        public string CueComercio;
        public string CueComentario;
        public int CueActiva;
        public string CueServidor;
        public int CuePuerto;
        public int? RiferoID;
    }

    // Mirrors DB Table PMProductos
    [Serializable()]
    public partial class PMProductosRecord : BaseRecord
	{
        public int ProductoID;
        public string ProNombre;
        public double ProPrecio;
        public int SuplidorID;
        public bool ProActivo;
    }

    // Mirrors DB Table PMSuplidores
    [Serializable()]
    public partial class PMSuplidoresRecord : BaseRecord
	{
        public int SuplidorID;
        public string SupNombre;
        public string SupComentario;
        public string SupInstrucciones;
        public double SupImpuesto;
        public double SupComision;
        public bool SupActivo;
    }

    // Mirrors DB Table RCuentasBancas
    [Serializable()]
    public partial class RCuentasBancasRecord : BaseRecord
	{
        public int CuentaBancaID;
        public int CuentaID;
        public int BancaID;
        public DateTime CBaDesde;
    }

    // Mirrors DB Table RF_BancaSorteo
    [Serializable()]
    public partial class RF_BancaSorteoRecord : BaseRecord
	{
        public int BancaID;
        public int SorteoID;
    }

    // Mirrors DB Table RF_EsquemaPago
    [Serializable()]
    public partial class RF_EsquemaPagoRecord : BaseRecord
	{
        public int EsquemaPagoID;
        public int SorteoTipoID;
        public string Nombre;
        public string Description;
    }

    // Mirrors DB Table RF_EsquemaPagoPremio
    [Serializable()]
    public partial class RF_EsquemaPagoPremioRecord : BaseRecord
	{
        public int EsquemaPagoPremioID;
        public int EsquemaPagoID;
        public int? SorteoID;
        public int SorteoTipoPremioID;
        public decimal Paga;
        public char? DiaSemana;
        public bool Activo;
    }

    // Mirrors DB Table RF_LimiteVenta
    [Serializable()]
    public partial class RF_LimiteVentaRecord : BaseRecord
	{
        public int LimiteVentaID;
        public int? SorteoID;
        public int? BancaID;
        public int? RiferoID;
        public int? ZonaID;
        public int? SorteoTipoJugadaID;
        public decimal Limite;
        public bool SinLimite;
    }

    // Mirrors DB Table RF_LimiteVentaDia
    [Serializable()]
    public partial class RF_LimiteVentaDiaRecord : BaseRecord
	{
        public int LimiteVentaDiaID;
        public DateTime Dia;
        public int SorteoID;
        public int BancaID;
        public int RiferoID;
        public int ZonaID;
        public int TipoJugadaID;
        public decimal Vendido;
    }

    // Mirrors DB Table RF_Loteria
    [Serializable()]
    public partial class RF_LoteriaRecord : BaseRecord
	{
        public int LoteriaID;
        public string Nombre;
        public string Referencia;
        public bool Activa;
    }

    // Mirrors DB Table RF_Sorteo
    [Serializable()]
    public partial class RF_SorteoRecord : BaseRecord
	{
        public int SorteoID;
        public string Nombre;
        public string Referencia;
        public int LoteriaID;
        public int SorteoTipoID;
        public int Activo;
    }

    // Mirrors DB Table RF_SorteoConfig
    [Serializable()]
    public partial class RF_SorteoConfigRecord : BaseRecord
	{
        public int SorteoConfigID;
        public int SorteoID;
        public string ConfigKey;
        public string ConfigValue;
        public bool Activo;
    }

    // Mirrors DB Table RF_SorteoDia
    [Serializable()]
    public partial class RF_SorteoDiaRecord : BaseRecord
	{
        public int SorteoDiaID;
        public int SorteoID;
        public DateTime Dia;
        public DateTime HoraInicioVentas;
        public DateTime HoraCierreVentas;
        public bool VentasCerradas;
        public string Premios;
        public DateTime? HoraPremios;
        public bool DiaCerrado;
        public DateTime? HoraCierreDia;
        public string Estado;
        public string Referencia;
        public bool PuedeReportar;
    }

    // Mirrors DB Table RF_SorteoTipo
    [Serializable()]
    public partial class RF_SorteoTipoRecord : BaseRecord
	{
        public int SorteoTipoID;
        public int LogicaKey;
        public string Nombre;
        public string Referencia;
        public string Descripcion;
    }

    // Mirrors DB Table RF_SorteoTipoJugada
    [Serializable()]
    public partial class RF_SorteoTipoJugadaRecord : BaseRecord
	{
        public int SorteoTipoJugadaID;
        public int SorteoTipoID;
        public string Nombre;
        public string Referencia;
        public int CamposNumero;
        public int NumeroMinimo;
        public int NumeroMaximo;
        public bool Activo;
        public string Opciones;
        public string Instrucciones;
    }

    // Mirrors DB Table RF_SorteoTipoPremio
    [Serializable()]
    public partial class RF_SorteoTipoPremioRecord : BaseRecord
	{
        public int SorteoTipoPremioID;
        public int SorteoTipoID;
        public int LogicaKey;
        public string Nombre;
        public string Descripcion;
        public bool Activo;
    }

    // Mirrors DB Table RF_Transaccion
    [Serializable()]
    public partial class RF_TransaccionRecord : BaseRecord
	{
        public int TransaccionID;
        public string Referencia;
        public string Serie;
        public int ReciboID;
        public int SolicitudID;
        public int SorteoDiaID;
        public int EsquemaPagoID;
        public DateTime FechaIngreso;
        public DateTime? FechaPago;
        public string Estado;
        public decimal Ingresos;
        public decimal? Pagos;
        public string Notas;
    }

    // Mirrors DB Table RF_TransaccionJugada
    [Serializable()]
    public partial class RF_TransaccionJugadaRecord : BaseRecord
	{
        public int TransaccionJugadaID;
        public int TransaccionID;
        public int SorteoTipoJugadaID;
        public string Numeros;
        public int Orden;
        public decimal Aposto;
        public decimal? Pago;
        public string Opciones;
    }

    // Mirrors DB Table RFuncionAdminUsuario
    [Serializable()]
    public partial class RFuncionAdminUsuarioRecord : BaseRecord
	{
        public int FuncionAdminUsuarioID;
        public int FuncionAdminID;
        public int UsuarioID;
    }

    // Mirrors DB Table RGruposUsuarios
    [Serializable()]
    public partial class RGruposUsuariosRecord : BaseRecord
	{
        public int GrupoUsuarioID;
        public int UsuarioID;
        public int GrupoID;
    }

    // Mirrors DB Table RRiferosUsuarios
    [Serializable()]
    public partial class RRiferosUsuariosRecord : BaseRecord
	{
        public int BancaUsuarioID;
        public int RiferoID;
        public int UsuarioID;
    }

    // Mirrors DB Table RWebProductoBanca
    [Serializable()]
    public partial class RWebProductoBancaRecord : BaseRecord
	{
        public int WebProductoBancaID;
        public int WebProductoID;
        public int BancaID;
    }

    // Mirrors DB Table RWebWindowBanca
    [Serializable()]
    public partial class RWebWindowBancaRecord : BaseRecord
	{
        public int WebWindowBancaID;
        public int WebWindowID;
        public int BancaID;
    }

    // Mirrors DB Table SFuncionAdmin
    [Serializable()]
    public partial class SFuncionAdminRecord : BaseRecord
	{
        public int FuncionAdminID;
        public int? ParentFuncionAdminID;
        public string Nombre;
        public bool Disponible;
    }

    // Mirrors DB Table SReportes
    [Serializable()]
    public partial class SReportesRecord : BaseRecord
	{
        public int ReporteID;
        public string RepNombre;
        public string RepFuente;
        public string RepArchivo;
        public int RepListOrden;
        public bool RepFecha;
        public bool RepRango;
        public bool RepLoteria;
        public bool RepRifero;
        public bool RepBanca;
        public bool RepTipo;
        public string RepOrder;
    }

    // Mirrors DB Table SWebProducto
    [Serializable()]
    public partial class SWebProductoRecord : BaseRecord
	{
        public int WebProductoID;
        public string Nombre;
        public string URL;
        public int SuplidorID;
        public bool Activo;
    }

    // Mirrors DB Table SWebProductoConfig
    [Serializable()]
    public partial class SWebProductoConfigRecord : BaseRecord
	{
        public int WebProductoConfigID;
        public int WebProductoID;
        public string Opcion;
        public string Valor;
        public int Modo;
        public bool Activo;
    }

    // Mirrors DB Table SWebWindow
    [Serializable()]
    public partial class SWebWindowRecord : BaseRecord
	{
        public int WebWindowID;
        public string Nombre;
        public string URL;
        public int Activa;
    }

    // Mirrors DB Table TempRiferos
    [Serializable()]
    public partial class TempRiferosRecord : BaseRecord
	{
        public int? RiferoID;
    }

    // Mirrors DB Table TEsquemas
    [Serializable()]
    public partial class TEsquemasRecord : BaseRecord
	{
        public int EsquemaID;
        public string EsqNombre;
    }

    // Mirrors DB Table TGrupos
    [Serializable()]
    public partial class TGruposRecord : BaseRecord
	{
        public int GrupoID;
        public string GruNombre;
        public string GruContacto;
        public string GruTelefono;
        public string GruCelular;
        public string GruComentario;
        public bool GruActivo;
        public string GruClientFooter;
        public string GruPrintHeader;
        public string GruPrintFooter;
        public bool GruLimiteGlo;
        public bool GruLimiteNum;
        public bool GruLimiteNumRifero;
        public bool GruLimiteGloBanca;
        public int GruMinutosAnula;
        public int GruDelayCierre;
        public int GruKeepAlive;
        public int GruMantenimiento;
        public bool GruLimiteTicBanca;
        public bool GruDosLoterias;
    }

    // Mirrors DB Table TLoterias
    [Serializable()]
    public partial class TLoteriasRecord : BaseRecord
	{
        public int LoteriaID;
        public string LotNombre;
        public string LotComentario;
        public bool LotActivo;
        public bool LotOculta;
        public string NombreResumido;
        public string Imagen;
    }

    // Mirrors DB Table VentaConPuto
    [Serializable()]
    public partial class VentaConPutoRecord : BaseRecord
	{
        public int TicketDetalleID;
        public int TicketID;
        public char TDeQP;
        public char TDeNumero;
        public double TDeCantidad;
        public decimal TDeCosto;
        public decimal TDePago;
        public char TDePagoTipo;
    }

    // Mirrors DB Table VP_Comisiones
    [Serializable()]
    public partial class VP_ComisionesRecord : BaseRecord
	{
        public int ComisionID;
        public int BancaID;
        public int VP_ProductoID;
        public double Porciento;
    }

    // Mirrors DB Table VP_Cuenta
    [Serializable()]
    public partial class VP_CuentaRecord : BaseRecord
	{
        public int CuentaID;
        public string Nombre;
        public int LogicaKey;
        public bool Activo;
        public int CuentaTipoID;
    }

    // Mirrors DB Table VP_CuentaConfig
    [Serializable()]
    public partial class VP_CuentaConfigRecord : BaseRecord
	{
        public int CuentaConfigID;
        public string ConfigKey;
        public string ConfigValue;
        public bool Activo;
        public int CuentaID;
    }

    // Mirrors DB Table VP_CuentaTipo
    [Serializable()]
    public partial class VP_CuentaTipoRecord : BaseRecord
	{
        public int CuentaTipoID;
        public string Nombre;
        public string Descripcion;
    }

    // Mirrors DB Table VP_HTransaccion
    [Serializable()]
    public partial class VP_HTransaccionRecord : BaseRecord
	{
        public int HTransaccionID;
        public int TransaccionID;
        public string Referencia;
        public string ReferenciaCliente;
        public int ReciboID;
        public int SolicitudID;
        public int ProductoID;
        public int SuplidorID;
        public int CuentaID;
        public DateTime FechaIngreso;
        public DateTime? FechaDescuento;
        public string Estado;
        public decimal Ingresos;
        public decimal? Descuentos;
        public bool Activo;
        public DateTime? FechaActualizacion;
        public int BancaID;
        public int UsuarioID;
    }

    // Mirrors DB Table VP_HTransaccionDetalle
    [Serializable()]
    public partial class VP_HTransaccionDetalleRecord : BaseRecord
	{
        public int HTransaccionDetalleID;
        public int TransaccionDetalleID;
        public int TransaccionID;
        public int ProductoCampoID;
        public string Referencia;
        public string ValorText;
        public double? ValorMonto;
        public decimal? Ingreso;
        public decimal? Descuento;
    }

    // Mirrors DB Table VP_LimiteVenta
    [Serializable()]
    public partial class VP_LimiteVentaRecord : BaseRecord
	{
        public int LimiteVentaID;
        public int? SuplidorID;
        public int? BancaID;
        public int? RiferoID;
        public int? ZonaID;
        public int? ProductoID;
        public decimal Limite;
        public bool SinLimite;
    }

    // Mirrors DB Table VP_LimiteVentaDia
    [Serializable()]
    public partial class VP_LimiteVentaDiaRecord : BaseRecord
	{
        public int LimiteVentaDiaID;
        public DateTime Dia;
        public int SuplidorID;
        public int BancaID;
        public int RiferoID;
        public int ZonaID;
        public int ProductoID;
        public decimal Vendido;
    }

    // Mirrors DB Table VP_LogComunicacion
    [Serializable()]
    public partial class VP_LogComunicacionRecord : BaseRecord
	{
        public int LogComunicacionID;
        public int CuentaID;
        public int? PinID;
        public int? TransaccionID;
        public string Origen;
        public string Destino;
        public string DataEnviada;
        public string DataRecibida;
        public string Estado;
        public DateTime Fecha;
    }

    // Mirrors DB Table VP_MarcaVehiculo
    [Serializable()]
    public partial class VP_MarcaVehiculoRecord : BaseRecord
	{
        public int MarcaID;
        public string Marca;
    }

    // Mirrors DB Table VP_ModeloVehiculo
    [Serializable()]
    public partial class VP_ModeloVehiculoRecord : BaseRecord
	{
        public int ModeloID;
        public string Modelo;
        public int MarcaID;
    }

    // Mirrors DB Table VP_Producto
    [Serializable()]
    public partial class VP_ProductoRecord : BaseRecord
	{
        public int ProductoID;
        public string Nombre;
        public string Referencia;
        public bool Activo;
        public int CuentaTipoID;
        public int LogicaKey;
    }

    // Mirrors DB Table VP_ProductoCampo
    [Serializable()]
    public partial class VP_ProductoCampoRecord : BaseRecord
	{
        public int ProductoCampoID;
        public string Nombre;
        public string Referencia;
        public string TipoDato;
        public string OpcionesReferencias;
        public string OpcionesNombres;
        public bool Activo;
        public int? ProductoID;
    }

    // Mirrors DB Table VP_ProductoConfig
    [Serializable()]
    public partial class VP_ProductoConfigRecord : BaseRecord
	{
        public int ProductoConfigID;
        public string ConfigKey;
        public string ConfigValue;
        public bool Activo;
        public int ProductoID;
    }

    // Mirrors DB Table VP_Suplidor
    [Serializable()]
    public partial class VP_SuplidorRecord : BaseRecord
	{
        public int SuplidorID;
        public string Nombre;
        public string Referencia;
        public bool Activo;
        public int CuentaID;
        public double Comision;
        public double Impuesto;
    }

    // Mirrors DB Table VP_SuplidorProducto
    [Serializable()]
    public partial class VP_SuplidorProductoRecord : BaseRecord
	{
        public int SuplidorID;
        public int ProductoID;
    }

    // Mirrors DB Table VP_Transaccion
    [Serializable()]
    public partial class VP_TransaccionRecord : BaseRecord
	{
        public int TransaccionID;
        public string Referencia;
        public string ReferenciaCliente;
        public int ReciboID;
        public int SolicitudID;
        public int ProductoID;
        public int SuplidorID;
        public int CuentaID;
        public DateTime FechaIngreso;
        public DateTime? FechaDescuento;
        public string Estado;
        public decimal Ingresos;
        public decimal? Descuentos;
        public bool Activo;
        public DateTime? FechaActualizacion;
        public int BancaID;
        public int UsuarioID;
    }

    // Mirrors DB Table VP_TransaccionDetalle
    [Serializable()]
    public partial class VP_TransaccionDetalleRecord : BaseRecord
	{
        public int TransaccionDetalleID;
        public int TransaccionID;
        public int ProductoCampoID;
        public string Referencia;
        public string ValorText;
        public double? ValorMonto;
        public decimal? Ingreso;
        public decimal? Descuento;
    }

}

