//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlujoCustomControl.BingoServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAR_Session", Namespace="mar.do")]
    [System.SerializableAttribute()]
    public partial class MAR_Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BancaField;
        
        private int UsuarioField;
        
        private int SesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrField;
        
        private int LastTckField;
        
        private int LastPinField;
        
        private int PrinterSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterFooterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Banca {
            get {
                return this.BancaField;
            }
            set {
                if ((this.BancaField.Equals(value) != true)) {
                    this.BancaField = value;
                    this.RaisePropertyChanged("Banca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((this.UsuarioField.Equals(value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Sesion {
            get {
                return this.SesionField;
            }
            set {
                if ((this.SesionField.Equals(value) != true)) {
                    this.SesionField = value;
                    this.RaisePropertyChanged("Sesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Err {
            get {
                return this.ErrField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrField, value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LastTck {
            get {
                return this.LastTckField;
            }
            set {
                if ((this.LastTckField.Equals(value) != true)) {
                    this.LastTckField = value;
                    this.RaisePropertyChanged("LastTck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int LastPin {
            get {
                return this.LastPinField;
            }
            set {
                if ((this.LastPinField.Equals(value) != true)) {
                    this.LastPinField = value;
                    this.RaisePropertyChanged("LastPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int PrinterSize {
            get {
                return this.PrinterSizeField;
            }
            set {
                if ((this.PrinterSizeField.Equals(value) != true)) {
                    this.PrinterSizeField = value;
                    this.RaisePropertyChanged("PrinterSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PrinterHeader {
            get {
                return this.PrinterHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterHeaderField, value) != true)) {
                    this.PrinterHeaderField = value;
                    this.RaisePropertyChanged("PrinterHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PrinterFooter {
            get {
                return this.PrinterFooterField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterFooterField, value) != true)) {
                    this.PrinterFooterField = value;
                    this.RaisePropertyChanged("PrinterFooter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="mar.do", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAR_BingoResponse", Namespace="mar.do")]
    [System.SerializableAttribute()]
    public partial class MAR_BingoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool OKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool OK {
            get {
                return this.OKField;
            }
            set {
                if ((this.OKField.Equals(value) != true)) {
                    this.OKField = value;
                    this.RaisePropertyChanged("OK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Err {
            get {
                return this.ErrField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrField, value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="mar.do", ConfigurationName="BingoServices.mar_bingoSoap")]
    public interface mar_bingoSoap {
        
        // CODEGEN: Generating message contract since element name pSesion from namespace mar.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="mar.do/CallJuegaMaxIndexFunction", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FlujoCustomControl.BingoServices.MAR_Session))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FlujoCustomControl.BingoServices.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FlujoCustomControl.BingoServices.MAR_BingoResponse))]
        FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionResponse CallJuegaMaxIndexFunction(FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="mar.do/CallJuegaMaxIndexFunction", ReplyAction="*")]
        System.IAsyncResult BeginCallJuegaMaxIndexFunction(FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequest request, System.AsyncCallback callback, object asyncState);
        
        FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionResponse EndCallJuegaMaxIndexFunction(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallJuegaMaxIndexFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallJuegaMaxIndexFunction", Namespace="mar.do", Order=0)]
        public FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequestBody Body;
        
        public CallJuegaMaxIndexFunctionRequest() {
        }
        
        public CallJuegaMaxIndexFunctionRequest(FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="mar.do")]
    public partial class CallJuegaMaxIndexFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pMetodo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public FlujoCustomControl.BingoServices.MAR_Session pSesion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public FlujoCustomControl.BingoServices.ArrayOfAnyType pParams;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pSolicitud;
        
        public CallJuegaMaxIndexFunctionRequestBody() {
        }
        
        public CallJuegaMaxIndexFunctionRequestBody(int pMetodo, FlujoCustomControl.BingoServices.MAR_Session pSesion, FlujoCustomControl.BingoServices.ArrayOfAnyType pParams, int pSolicitud) {
            this.pMetodo = pMetodo;
            this.pSesion = pSesion;
            this.pParams = pParams;
            this.pSolicitud = pSolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallJuegaMaxIndexFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallJuegaMaxIndexFunctionResponse", Namespace="mar.do", Order=0)]
        public FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionResponseBody Body;
        
        public CallJuegaMaxIndexFunctionResponse() {
        }
        
        public CallJuegaMaxIndexFunctionResponse(FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="mar.do")]
    public partial class CallJuegaMaxIndexFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FlujoCustomControl.BingoServices.MAR_BingoResponse CallJuegaMaxIndexFunctionResult;
        
        public CallJuegaMaxIndexFunctionResponseBody() {
        }
        
        public CallJuegaMaxIndexFunctionResponseBody(FlujoCustomControl.BingoServices.MAR_BingoResponse CallJuegaMaxIndexFunctionResult) {
            this.CallJuegaMaxIndexFunctionResult = CallJuegaMaxIndexFunctionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mar_bingoSoapChannel : FlujoCustomControl.BingoServices.mar_bingoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallJuegaMaxIndexFunctionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CallJuegaMaxIndexFunctionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FlujoCustomControl.BingoServices.MAR_BingoResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FlujoCustomControl.BingoServices.MAR_BingoResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mar_bingoSoapClient : System.ServiceModel.ClientBase<FlujoCustomControl.BingoServices.mar_bingoSoap>, FlujoCustomControl.BingoServices.mar_bingoSoap {
        
        private BeginOperationDelegate onBeginCallJuegaMaxIndexFunctionDelegate;
        
        private EndOperationDelegate onEndCallJuegaMaxIndexFunctionDelegate;
        
        private System.Threading.SendOrPostCallback onCallJuegaMaxIndexFunctionCompletedDelegate;
        
        public mar_bingoSoapClient() {
        }
        
        public mar_bingoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mar_bingoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mar_bingoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mar_bingoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CallJuegaMaxIndexFunctionCompletedEventArgs> CallJuegaMaxIndexFunctionCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionResponse FlujoCustomControl.BingoServices.mar_bingoSoap.CallJuegaMaxIndexFunction(FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequest request) {
            return base.Channel.CallJuegaMaxIndexFunction(request);
        }
        
        public FlujoCustomControl.BingoServices.MAR_BingoResponse CallJuegaMaxIndexFunction(int pMetodo, FlujoCustomControl.BingoServices.MAR_Session pSesion, FlujoCustomControl.BingoServices.ArrayOfAnyType pParams, int pSolicitud) {
            FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequest inValue = new FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequest();
            inValue.Body = new FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequestBody();
            inValue.Body.pMetodo = pMetodo;
            inValue.Body.pSesion = pSesion;
            inValue.Body.pParams = pParams;
            inValue.Body.pSolicitud = pSolicitud;
            FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionResponse retVal = ((FlujoCustomControl.BingoServices.mar_bingoSoap)(this)).CallJuegaMaxIndexFunction(inValue);
            return retVal.Body.CallJuegaMaxIndexFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FlujoCustomControl.BingoServices.mar_bingoSoap.BeginCallJuegaMaxIndexFunction(FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCallJuegaMaxIndexFunction(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCallJuegaMaxIndexFunction(int pMetodo, FlujoCustomControl.BingoServices.MAR_Session pSesion, FlujoCustomControl.BingoServices.ArrayOfAnyType pParams, int pSolicitud, System.AsyncCallback callback, object asyncState) {
            FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequest inValue = new FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequest();
            inValue.Body = new FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionRequestBody();
            inValue.Body.pMetodo = pMetodo;
            inValue.Body.pSesion = pSesion;
            inValue.Body.pParams = pParams;
            inValue.Body.pSolicitud = pSolicitud;
            return ((FlujoCustomControl.BingoServices.mar_bingoSoap)(this)).BeginCallJuegaMaxIndexFunction(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionResponse FlujoCustomControl.BingoServices.mar_bingoSoap.EndCallJuegaMaxIndexFunction(System.IAsyncResult result) {
            return base.Channel.EndCallJuegaMaxIndexFunction(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public FlujoCustomControl.BingoServices.MAR_BingoResponse EndCallJuegaMaxIndexFunction(System.IAsyncResult result) {
            FlujoCustomControl.BingoServices.CallJuegaMaxIndexFunctionResponse retVal = ((FlujoCustomControl.BingoServices.mar_bingoSoap)(this)).EndCallJuegaMaxIndexFunction(result);
            return retVal.Body.CallJuegaMaxIndexFunctionResult;
        }
        
        private System.IAsyncResult OnBeginCallJuegaMaxIndexFunction(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pMetodo = ((int)(inValues[0]));
            FlujoCustomControl.BingoServices.MAR_Session pSesion = ((FlujoCustomControl.BingoServices.MAR_Session)(inValues[1]));
            FlujoCustomControl.BingoServices.ArrayOfAnyType pParams = ((FlujoCustomControl.BingoServices.ArrayOfAnyType)(inValues[2]));
            int pSolicitud = ((int)(inValues[3]));
            return this.BeginCallJuegaMaxIndexFunction(pMetodo, pSesion, pParams, pSolicitud, callback, asyncState);
        }
        
        private object[] OnEndCallJuegaMaxIndexFunction(System.IAsyncResult result) {
            FlujoCustomControl.BingoServices.MAR_BingoResponse retVal = this.EndCallJuegaMaxIndexFunction(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCallJuegaMaxIndexFunctionCompleted(object state) {
            if ((this.CallJuegaMaxIndexFunctionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CallJuegaMaxIndexFunctionCompleted(this, new CallJuegaMaxIndexFunctionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CallJuegaMaxIndexFunctionAsync(int pMetodo, FlujoCustomControl.BingoServices.MAR_Session pSesion, FlujoCustomControl.BingoServices.ArrayOfAnyType pParams, int pSolicitud) {
            this.CallJuegaMaxIndexFunctionAsync(pMetodo, pSesion, pParams, pSolicitud, null);
        }
        
        public void CallJuegaMaxIndexFunctionAsync(int pMetodo, FlujoCustomControl.BingoServices.MAR_Session pSesion, FlujoCustomControl.BingoServices.ArrayOfAnyType pParams, int pSolicitud, object userState) {
            if ((this.onBeginCallJuegaMaxIndexFunctionDelegate == null)) {
                this.onBeginCallJuegaMaxIndexFunctionDelegate = new BeginOperationDelegate(this.OnBeginCallJuegaMaxIndexFunction);
            }
            if ((this.onEndCallJuegaMaxIndexFunctionDelegate == null)) {
                this.onEndCallJuegaMaxIndexFunctionDelegate = new EndOperationDelegate(this.OnEndCallJuegaMaxIndexFunction);
            }
            if ((this.onCallJuegaMaxIndexFunctionCompletedDelegate == null)) {
                this.onCallJuegaMaxIndexFunctionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCallJuegaMaxIndexFunctionCompleted);
            }
            base.InvokeAsync(this.onBeginCallJuegaMaxIndexFunctionDelegate, new object[] {
                        pMetodo,
                        pSesion,
                        pParams,
                        pSolicitud}, this.onEndCallJuegaMaxIndexFunctionDelegate, this.onCallJuegaMaxIndexFunctionCompletedDelegate, userState);
        }
    }
}
