//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMarWPFWin7.Domain.HaciendaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAR_Session", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MAR_Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BancaField;
        
        private int UsuarioField;
        
        private int SesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrField;
        
        private int LastTckField;
        
        private int LastPinField;
        
        private int PrinterSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterFooterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Banca {
            get {
                return this.BancaField;
            }
            set {
                if ((this.BancaField.Equals(value) != true)) {
                    this.BancaField = value;
                    this.RaisePropertyChanged("Banca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((this.UsuarioField.Equals(value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Sesion {
            get {
                return this.SesionField;
            }
            set {
                if ((this.SesionField.Equals(value) != true)) {
                    this.SesionField = value;
                    this.RaisePropertyChanged("Sesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Err {
            get {
                return this.ErrField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrField, value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LastTck {
            get {
                return this.LastTckField;
            }
            set {
                if ((this.LastTckField.Equals(value) != true)) {
                    this.LastTckField = value;
                    this.RaisePropertyChanged("LastTck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int LastPin {
            get {
                return this.LastPinField;
            }
            set {
                if ((this.LastPinField.Equals(value) != true)) {
                    this.LastPinField = value;
                    this.RaisePropertyChanged("LastPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int PrinterSize {
            get {
                return this.PrinterSizeField;
            }
            set {
                if ((this.PrinterSizeField.Equals(value) != true)) {
                    this.PrinterSizeField = value;
                    this.RaisePropertyChanged("PrinterSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PrinterHeader {
            get {
                return this.PrinterHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterHeaderField, value) != true)) {
                    this.PrinterHeaderField = value;
                    this.RaisePropertyChanged("PrinterHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PrinterFooter {
            get {
                return this.PrinterFooterField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterFooterField, value) != true)) {
                    this.PrinterFooterField = value;
                    this.RaisePropertyChanged("PrinterFooter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAR_HaciendaResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MAR_HaciendaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool OKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool OK {
            get {
                return this.OKField;
            }
            set {
                if ((this.OKField.Equals(value) != true)) {
                    this.OKField = value;
                    this.RaisePropertyChanged("OK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Err {
            get {
                return this.ErrField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrField, value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HaciendaService.mar_haciendaSoap")]
    public interface mar_haciendaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pSesion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallHaciendaFuncion", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClienteMarWPFWin7.Domain.HaciendaService.MAR_Session))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClienteMarWPFWin7.Domain.HaciendaService.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClienteMarWPFWin7.Domain.HaciendaService.MAR_HaciendaResponse))]
        ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionResponse CallHaciendaFuncion(ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallHaciendaFuncion", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionResponse> CallHaciendaFuncionAsync(ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallHaciendaFuncionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallHaciendaFuncion", Namespace="http://tempuri.org/", Order=0)]
        public ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequestBody Body;
        
        public CallHaciendaFuncionRequest() {
        }
        
        public CallHaciendaFuncionRequest(ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallHaciendaFuncionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pMetodo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClienteMarWPFWin7.Domain.HaciendaService.MAR_Session pSesion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClienteMarWPFWin7.Domain.HaciendaService.ArrayOfAnyType pParams;
        
        public CallHaciendaFuncionRequestBody() {
        }
        
        public CallHaciendaFuncionRequestBody(int pMetodo, ClienteMarWPFWin7.Domain.HaciendaService.MAR_Session pSesion, ClienteMarWPFWin7.Domain.HaciendaService.ArrayOfAnyType pParams) {
            this.pMetodo = pMetodo;
            this.pSesion = pSesion;
            this.pParams = pParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallHaciendaFuncionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallHaciendaFuncionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionResponseBody Body;
        
        public CallHaciendaFuncionResponse() {
        }
        
        public CallHaciendaFuncionResponse(ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallHaciendaFuncionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteMarWPFWin7.Domain.HaciendaService.MAR_HaciendaResponse CallHaciendaFuncionResult;
        
        public CallHaciendaFuncionResponseBody() {
        }
        
        public CallHaciendaFuncionResponseBody(ClienteMarWPFWin7.Domain.HaciendaService.MAR_HaciendaResponse CallHaciendaFuncionResult) {
            this.CallHaciendaFuncionResult = CallHaciendaFuncionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mar_haciendaSoapChannel : ClienteMarWPFWin7.Domain.HaciendaService.mar_haciendaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mar_haciendaSoapClient : System.ServiceModel.ClientBase<ClienteMarWPFWin7.Domain.HaciendaService.mar_haciendaSoap>, ClienteMarWPFWin7.Domain.HaciendaService.mar_haciendaSoap {
        
        public mar_haciendaSoapClient() {
        }
        
        public mar_haciendaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mar_haciendaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mar_haciendaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mar_haciendaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionResponse ClienteMarWPFWin7.Domain.HaciendaService.mar_haciendaSoap.CallHaciendaFuncion(ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequest request) {
            return base.Channel.CallHaciendaFuncion(request);
        }
        
        public ClienteMarWPFWin7.Domain.HaciendaService.MAR_HaciendaResponse CallHaciendaFuncion(int pMetodo, ClienteMarWPFWin7.Domain.HaciendaService.MAR_Session pSesion, ClienteMarWPFWin7.Domain.HaciendaService.ArrayOfAnyType pParams) {
            ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequest inValue = new ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequest();
            inValue.Body = new ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequestBody();
            inValue.Body.pMetodo = pMetodo;
            inValue.Body.pSesion = pSesion;
            inValue.Body.pParams = pParams;
            ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionResponse retVal = ((ClienteMarWPFWin7.Domain.HaciendaService.mar_haciendaSoap)(this)).CallHaciendaFuncion(inValue);
            return retVal.Body.CallHaciendaFuncionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionResponse> ClienteMarWPFWin7.Domain.HaciendaService.mar_haciendaSoap.CallHaciendaFuncionAsync(ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequest request) {
            return base.Channel.CallHaciendaFuncionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionResponse> CallHaciendaFuncionAsync(int pMetodo, ClienteMarWPFWin7.Domain.HaciendaService.MAR_Session pSesion, ClienteMarWPFWin7.Domain.HaciendaService.ArrayOfAnyType pParams) {
            ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequest inValue = new ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequest();
            inValue.Body = new ClienteMarWPFWin7.Domain.HaciendaService.CallHaciendaFuncionRequestBody();
            inValue.Body.pMetodo = pMetodo;
            inValue.Body.pSesion = pSesion;
            inValue.Body.pParams = pParams;
            return ((ClienteMarWPFWin7.Domain.HaciendaService.mar_haciendaSoap)(this)).CallHaciendaFuncionAsync(inValue);
        }
    }
}
