//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaciendaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAR_Session", Namespace="http://tempuri.org/")]
    public partial class MAR_Session : object
    {
        
        private int BancaField;
        
        private int UsuarioField;
        
        private int SesionField;
        
        private string ErrField;
        
        private int LastTckField;
        
        private int LastPinField;
        
        private int PrinterSizeField;
        
        private string PrinterHeaderField;
        
        private string PrinterFooterField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Banca
        {
            get
            {
                return this.BancaField;
            }
            set
            {
                this.BancaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Sesion
        {
            get
            {
                return this.SesionField;
            }
            set
            {
                this.SesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Err
        {
            get
            {
                return this.ErrField;
            }
            set
            {
                this.ErrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LastTck
        {
            get
            {
                return this.LastTckField;
            }
            set
            {
                this.LastTckField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int LastPin
        {
            get
            {
                return this.LastPinField;
            }
            set
            {
                this.LastPinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int PrinterSize
        {
            get
            {
                return this.PrinterSizeField;
            }
            set
            {
                this.PrinterSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PrinterHeader
        {
            get
            {
                return this.PrinterHeaderField;
            }
            set
            {
                this.PrinterHeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PrinterFooter
        {
            get
            {
                return this.PrinterFooterField;
            }
            set
            {
                this.PrinterFooterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    public class ArrayOfAnyType : System.Collections.Generic.List<object>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAR_HaciendaResponse", Namespace="http://tempuri.org/")]
    public partial class MAR_HaciendaResponse : object
    {
        
        private bool OKField;
        
        private string MensajeField;
        
        private string RespuestaField;
        
        private string ErrField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool OK
        {
            get
            {
                return this.OKField;
            }
            set
            {
                this.OKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Err
        {
            get
            {
                return this.ErrField;
            }
            set
            {
                this.ErrField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HaciendaService.mar_haciendaSoap")]
    public interface mar_haciendaSoap
    {
        
        // CODEGEN: Generating message contract since element name pSesion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallHaciendaFuncion", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaciendaService.MAR_Session))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaciendaService.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaciendaService.MAR_HaciendaResponse))]
        HaciendaService.CallHaciendaFuncionResponse CallHaciendaFuncion(HaciendaService.CallHaciendaFuncionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallHaciendaFuncion", ReplyAction="*")]
        System.Threading.Tasks.Task<HaciendaService.CallHaciendaFuncionResponse> CallHaciendaFuncionAsync(HaciendaService.CallHaciendaFuncionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallHaciendaFuncionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallHaciendaFuncion", Namespace="http://tempuri.org/", Order=0)]
        public HaciendaService.CallHaciendaFuncionRequestBody Body;
        
        public CallHaciendaFuncionRequest()
        {
        }
        
        public CallHaciendaFuncionRequest(HaciendaService.CallHaciendaFuncionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallHaciendaFuncionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pMetodo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public HaciendaService.MAR_Session pSesion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public HaciendaService.ArrayOfAnyType pParams;
        
        public CallHaciendaFuncionRequestBody()
        {
        }
        
        public CallHaciendaFuncionRequestBody(int pMetodo, HaciendaService.MAR_Session pSesion, HaciendaService.ArrayOfAnyType pParams)
        {
            this.pMetodo = pMetodo;
            this.pSesion = pSesion;
            this.pParams = pParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallHaciendaFuncionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallHaciendaFuncionResponse", Namespace="http://tempuri.org/", Order=0)]
        public HaciendaService.CallHaciendaFuncionResponseBody Body;
        
        public CallHaciendaFuncionResponse()
        {
        }
        
        public CallHaciendaFuncionResponse(HaciendaService.CallHaciendaFuncionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallHaciendaFuncionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HaciendaService.MAR_HaciendaResponse CallHaciendaFuncionResult;
        
        public CallHaciendaFuncionResponseBody()
        {
        }
        
        public CallHaciendaFuncionResponseBody(HaciendaService.MAR_HaciendaResponse CallHaciendaFuncionResult)
        {
            this.CallHaciendaFuncionResult = CallHaciendaFuncionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface mar_haciendaSoapChannel : HaciendaService.mar_haciendaSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class mar_haciendaSoapClient : System.ServiceModel.ClientBase<HaciendaService.mar_haciendaSoap>, HaciendaService.mar_haciendaSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public mar_haciendaSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(mar_haciendaSoapClient.GetBindingForEndpoint(endpointConfiguration), mar_haciendaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public mar_haciendaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(mar_haciendaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public mar_haciendaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(mar_haciendaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public mar_haciendaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HaciendaService.CallHaciendaFuncionResponse HaciendaService.mar_haciendaSoap.CallHaciendaFuncion(HaciendaService.CallHaciendaFuncionRequest request)
        {
            return base.Channel.CallHaciendaFuncion(request);
        }
        
        public HaciendaService.MAR_HaciendaResponse CallHaciendaFuncion(int pMetodo, HaciendaService.MAR_Session pSesion, HaciendaService.ArrayOfAnyType pParams)
        {
            HaciendaService.CallHaciendaFuncionRequest inValue = new HaciendaService.CallHaciendaFuncionRequest();
            inValue.Body = new HaciendaService.CallHaciendaFuncionRequestBody();
            inValue.Body.pMetodo = pMetodo;
            inValue.Body.pSesion = pSesion;
            inValue.Body.pParams = pParams;
            HaciendaService.CallHaciendaFuncionResponse retVal = ((HaciendaService.mar_haciendaSoap)(this)).CallHaciendaFuncion(inValue);
            return retVal.Body.CallHaciendaFuncionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HaciendaService.CallHaciendaFuncionResponse> HaciendaService.mar_haciendaSoap.CallHaciendaFuncionAsync(HaciendaService.CallHaciendaFuncionRequest request)
        {
            return base.Channel.CallHaciendaFuncionAsync(request);
        }
        
        public System.Threading.Tasks.Task<HaciendaService.CallHaciendaFuncionResponse> CallHaciendaFuncionAsync(int pMetodo, HaciendaService.MAR_Session pSesion, HaciendaService.ArrayOfAnyType pParams)
        {
            HaciendaService.CallHaciendaFuncionRequest inValue = new HaciendaService.CallHaciendaFuncionRequest();
            inValue.Body = new HaciendaService.CallHaciendaFuncionRequestBody();
            inValue.Body.pMetodo = pMetodo;
            inValue.Body.pSesion = pSesion;
            inValue.Body.pParams = pParams;
            return ((HaciendaService.mar_haciendaSoap)(this)).CallHaciendaFuncionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.mar_haciendaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.mar_haciendaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.mar_haciendaSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:14217/mar-hacienda.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.mar_haciendaSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:14217/mar-hacienda.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            mar_haciendaSoap,
            
            mar_haciendaSoap12,
        }
    }
}
