//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlujoCustomControl.FlujoServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAR_Session", Namespace="mar.do")]
    [System.SerializableAttribute()]
    public partial class MAR_Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BancaField;
        
        private int UsuarioField;
        
        private int SesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrField;
        
        private int LastTckField;
        
        private int LastPinField;
        
        private int PrinterSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterFooterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Banca {
            get {
                return this.BancaField;
            }
            set {
                if ((this.BancaField.Equals(value) != true)) {
                    this.BancaField = value;
                    this.RaisePropertyChanged("Banca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((this.UsuarioField.Equals(value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Sesion {
            get {
                return this.SesionField;
            }
            set {
                if ((this.SesionField.Equals(value) != true)) {
                    this.SesionField = value;
                    this.RaisePropertyChanged("Sesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Err {
            get {
                return this.ErrField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrField, value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LastTck {
            get {
                return this.LastTckField;
            }
            set {
                if ((this.LastTckField.Equals(value) != true)) {
                    this.LastTckField = value;
                    this.RaisePropertyChanged("LastTck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int LastPin {
            get {
                return this.LastPinField;
            }
            set {
                if ((this.LastPinField.Equals(value) != true)) {
                    this.LastPinField = value;
                    this.RaisePropertyChanged("LastPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int PrinterSize {
            get {
                return this.PrinterSizeField;
            }
            set {
                if ((this.PrinterSizeField.Equals(value) != true)) {
                    this.PrinterSizeField = value;
                    this.RaisePropertyChanged("PrinterSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PrinterHeader {
            get {
                return this.PrinterHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterHeaderField, value) != true)) {
                    this.PrinterHeaderField = value;
                    this.RaisePropertyChanged("PrinterHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PrinterFooter {
            get {
                return this.PrinterFooterField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterFooterField, value) != true)) {
                    this.PrinterFooterField = value;
                    this.RaisePropertyChanged("PrinterFooter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="mar.do", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAR_FlujoResponse", Namespace="mar.do")]
    [System.SerializableAttribute()]
    public partial class MAR_FlujoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool OKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool OK {
            get {
                return this.OKField;
            }
            set {
                if ((this.OKField.Equals(value) != true)) {
                    this.OKField = value;
                    this.RaisePropertyChanged("OK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Err {
            get {
                return this.ErrField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrField, value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="mar.do", ConfigurationName="FlujoServices.mar_flujoSoap")]
    public interface mar_flujoSoap {
        
        // CODEGEN: Generating message contract since element name pSesion from namespace mar.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="mar.do/CallFlujoIndexFunction", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FlujoCustomControl.FlujoServices.MAR_Session))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FlujoCustomControl.FlujoServices.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FlujoCustomControl.FlujoServices.MAR_FlujoResponse))]
        FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionResponse CallFlujoIndexFunction(FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="mar.do/CallFlujoIndexFunction", ReplyAction="*")]
        System.IAsyncResult BeginCallFlujoIndexFunction(FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequest request, System.AsyncCallback callback, object asyncState);
        
        FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionResponse EndCallFlujoIndexFunction(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallFlujoIndexFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallFlujoIndexFunction", Namespace="mar.do", Order=0)]
        public FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequestBody Body;
        
        public CallFlujoIndexFunctionRequest() {
        }
        
        public CallFlujoIndexFunctionRequest(FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="mar.do")]
    public partial class CallFlujoIndexFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pMetodo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public FlujoCustomControl.FlujoServices.MAR_Session pSesion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public FlujoCustomControl.FlujoServices.ArrayOfAnyType pParams;
        
        public CallFlujoIndexFunctionRequestBody() {
        }
        
        public CallFlujoIndexFunctionRequestBody(int pMetodo, FlujoCustomControl.FlujoServices.MAR_Session pSesion, FlujoCustomControl.FlujoServices.ArrayOfAnyType pParams) {
            this.pMetodo = pMetodo;
            this.pSesion = pSesion;
            this.pParams = pParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallFlujoIndexFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallFlujoIndexFunctionResponse", Namespace="mar.do", Order=0)]
        public FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionResponseBody Body;
        
        public CallFlujoIndexFunctionResponse() {
        }
        
        public CallFlujoIndexFunctionResponse(FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="mar.do")]
    public partial class CallFlujoIndexFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FlujoCustomControl.FlujoServices.MAR_FlujoResponse CallFlujoIndexFunctionResult;
        
        public CallFlujoIndexFunctionResponseBody() {
        }
        
        public CallFlujoIndexFunctionResponseBody(FlujoCustomControl.FlujoServices.MAR_FlujoResponse CallFlujoIndexFunctionResult) {
            this.CallFlujoIndexFunctionResult = CallFlujoIndexFunctionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mar_flujoSoapChannel : FlujoCustomControl.FlujoServices.mar_flujoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallFlujoIndexFunctionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CallFlujoIndexFunctionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FlujoCustomControl.FlujoServices.MAR_FlujoResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FlujoCustomControl.FlujoServices.MAR_FlujoResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mar_flujoSoapClient : System.ServiceModel.ClientBase<FlujoCustomControl.FlujoServices.mar_flujoSoap>, FlujoCustomControl.FlujoServices.mar_flujoSoap {
        
        private BeginOperationDelegate onBeginCallFlujoIndexFunctionDelegate;
        
        private EndOperationDelegate onEndCallFlujoIndexFunctionDelegate;
        
        private System.Threading.SendOrPostCallback onCallFlujoIndexFunctionCompletedDelegate;
        
        public mar_flujoSoapClient() {
        }
        
        public mar_flujoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mar_flujoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mar_flujoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mar_flujoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CallFlujoIndexFunctionCompletedEventArgs> CallFlujoIndexFunctionCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionResponse FlujoCustomControl.FlujoServices.mar_flujoSoap.CallFlujoIndexFunction(FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequest request) {
            return base.Channel.CallFlujoIndexFunction(request);
        }
        
        public FlujoCustomControl.FlujoServices.MAR_FlujoResponse CallFlujoIndexFunction(int pMetodo, FlujoCustomControl.FlujoServices.MAR_Session pSesion, FlujoCustomControl.FlujoServices.ArrayOfAnyType pParams) {
            FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequest inValue = new FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequest();
            inValue.Body = new FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequestBody();
            inValue.Body.pMetodo = pMetodo;
            inValue.Body.pSesion = pSesion;
            inValue.Body.pParams = pParams;
            FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionResponse retVal = ((FlujoCustomControl.FlujoServices.mar_flujoSoap)(this)).CallFlujoIndexFunction(inValue);
            return retVal.Body.CallFlujoIndexFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FlujoCustomControl.FlujoServices.mar_flujoSoap.BeginCallFlujoIndexFunction(FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCallFlujoIndexFunction(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCallFlujoIndexFunction(int pMetodo, FlujoCustomControl.FlujoServices.MAR_Session pSesion, FlujoCustomControl.FlujoServices.ArrayOfAnyType pParams, System.AsyncCallback callback, object asyncState) {
            FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequest inValue = new FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequest();
            inValue.Body = new FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionRequestBody();
            inValue.Body.pMetodo = pMetodo;
            inValue.Body.pSesion = pSesion;
            inValue.Body.pParams = pParams;
            return ((FlujoCustomControl.FlujoServices.mar_flujoSoap)(this)).BeginCallFlujoIndexFunction(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionResponse FlujoCustomControl.FlujoServices.mar_flujoSoap.EndCallFlujoIndexFunction(System.IAsyncResult result) {
            return base.Channel.EndCallFlujoIndexFunction(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public FlujoCustomControl.FlujoServices.MAR_FlujoResponse EndCallFlujoIndexFunction(System.IAsyncResult result) {
            FlujoCustomControl.FlujoServices.CallFlujoIndexFunctionResponse retVal = ((FlujoCustomControl.FlujoServices.mar_flujoSoap)(this)).EndCallFlujoIndexFunction(result);
            return retVal.Body.CallFlujoIndexFunctionResult;
        }
        
        private System.IAsyncResult OnBeginCallFlujoIndexFunction(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pMetodo = ((int)(inValues[0]));
            FlujoCustomControl.FlujoServices.MAR_Session pSesion = ((FlujoCustomControl.FlujoServices.MAR_Session)(inValues[1]));
            FlujoCustomControl.FlujoServices.ArrayOfAnyType pParams = ((FlujoCustomControl.FlujoServices.ArrayOfAnyType)(inValues[2]));
            return this.BeginCallFlujoIndexFunction(pMetodo, pSesion, pParams, callback, asyncState);
        }
        
        private object[] OnEndCallFlujoIndexFunction(System.IAsyncResult result) {
            FlujoCustomControl.FlujoServices.MAR_FlujoResponse retVal = this.EndCallFlujoIndexFunction(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCallFlujoIndexFunctionCompleted(object state) {
            if ((this.CallFlujoIndexFunctionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CallFlujoIndexFunctionCompleted(this, new CallFlujoIndexFunctionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CallFlujoIndexFunctionAsync(int pMetodo, FlujoCustomControl.FlujoServices.MAR_Session pSesion, FlujoCustomControl.FlujoServices.ArrayOfAnyType pParams) {
            this.CallFlujoIndexFunctionAsync(pMetodo, pSesion, pParams, null);
        }
        
        public void CallFlujoIndexFunctionAsync(int pMetodo, FlujoCustomControl.FlujoServices.MAR_Session pSesion, FlujoCustomControl.FlujoServices.ArrayOfAnyType pParams, object userState) {
            if ((this.onBeginCallFlujoIndexFunctionDelegate == null)) {
                this.onBeginCallFlujoIndexFunctionDelegate = new BeginOperationDelegate(this.OnBeginCallFlujoIndexFunction);
            }
            if ((this.onEndCallFlujoIndexFunctionDelegate == null)) {
                this.onEndCallFlujoIndexFunctionDelegate = new EndOperationDelegate(this.OnEndCallFlujoIndexFunction);
            }
            if ((this.onCallFlujoIndexFunctionCompletedDelegate == null)) {
                this.onCallFlujoIndexFunctionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCallFlujoIndexFunctionCompleted);
            }
            base.InvokeAsync(this.onBeginCallFlujoIndexFunctionDelegate, new object[] {
                        pMetodo,
                        pSesion,
                        pParams}, this.onEndCallFlujoIndexFunctionDelegate, this.onCallFlujoIndexFunctionCompletedDelegate, userState);
        }
    }
}
